-- Table: public.tb_customer

-- DROP TABLE IF EXISTS public.tb_customer;

CREATE TABLE IF NOT EXISTS public.tb_customer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    avatar character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    idno character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    idno_issued_date timestamp without time zone,
    birth_date timestamp without time zone,
    sex integer,
    phone character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    email character varying(300) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    token character varying(500) COLLATE pg_catalog."default",
    address character varying(500) COLLATE pg_catalog."default",
    password character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    is_delete integer DEFAULT 1,
    note text COLLATE pg_catalog."default",
    status integer DEFAULT 0,
    maker_date timestamp without time zone,
    CONSTRAINT tb_customers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tb_customer
    OWNER to postgres;

COMMENT ON COLUMN public.tb_customer.id
    IS 'Số sequence';

COMMENT ON COLUMN public.tb_customer.avatar
    IS 'Hình đại diện';

COMMENT ON COLUMN public.tb_customer.code
    IS 'Mã';

COMMENT ON COLUMN public.tb_customer.name
    IS 'Tên cá nhân /  Người đại diện';

COMMENT ON COLUMN public.tb_customer.idno
    IS 'Số cmnd/ passport';

COMMENT ON COLUMN public.tb_customer.idno_issued_date
    IS 'Ngày cấp cmnd/ passport';

COMMENT ON COLUMN public.tb_customer.birth_date
    IS 'Ngày sinh';

COMMENT ON COLUMN public.tb_customer.sex
    IS 'Giới tính: + 1: Nam + 0: Nữ';

COMMENT ON COLUMN public.tb_customer.phone
    IS 'Số điện thoại';

COMMENT ON COLUMN public.tb_customer.email
    IS 'Email';

COMMENT ON COLUMN public.tb_customer.address
    IS 'Địa chỉ liên hệ';

COMMENT ON COLUMN public.tb_customer.is_delete
    IS 'Giá trị dữ liệu có được xoá hay không 0: không được xoá 1: được xoá';

COMMENT ON COLUMN public.tb_customer.note
    IS 'Ghi chú';

COMMENT ON COLUMN public.tb_customer.status
    IS 'Tình trạng dữ liệu: 1: Active, 0: Inactive';

COMMENT ON COLUMN public.tb_customer.maker_id
    IS 'Người tạo';

COMMENT ON COLUMN public.tb_customer.maker_date
    IS 'Ngày tạo';