DROP TABLE public.tb_config_menu;
 CREATE TABLE public.tb_config_menu (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    position character varying(255) COLLATE pg_catalog."default" NOT NULL,
    container json,
    orders integer DEFAULT 0,
    is_delete integer DEFAULT 1,
    note text COLLATE pg_catalog."default",
    status integer DEFAULT 0,
    maker_id bigint NOT NULL,
    maker_date timestamp without time zone,
    CONSTRAINT tb_config_menu_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
    public.tb_config_menu OWNER to postgres;

COMMENT ON COLUMN public.tb_config_menu.id IS 'Số sequence';

COMMENT ON COLUMN public.tb_config_menu.container IS 'Danh sách id trang/nhóm danh muc';

COMMENT ON COLUMN public.tb_config_menu.is_delete IS 'Giá trị dữ liệu có được xoá hay không 0: không được xoá 1: được xoá';

COMMENT ON COLUMN public.tb_config_menu.status IS 'Tình trạng dữ liệu: 1: Active, 0: Inactive';

COMMENT ON COLUMN public.tb_config_menu.maker_id IS 'Người tạo';

COMMENT ON COLUMN public.tb_config_menu.maker_date IS 'Ngày tạo';

INSERT INTO
      public.tb_config_menu

VALUES
    (
        1,
        'Menu Header',
        'menuMain',
        NULL,
        1,
        1,
        '',
        1,
        7,
        '2022-11-14'
    ),
    (
        2,
        'Menu Footer : Về Chúng Tôi',
        'about',
          NULL,
        3,
        1,
        '',
        1,
        1,
        '2022-09-28'
    ),
    (
        3,
        'Menu Footer : Sản phẩm & Dịch vụ',
        'service',
          NULL,
        4,
        1,
        '',
        1,
        1,
        '2022-09-28'
    ),
    (
        4,
        'Menu Footer : Tin tức',
        'content',
          NULL,
        5,
        1,
        '',
        1,
        1,
        '2022-09-28'
    ),
    (
        7,
        'Menu Footer : Hỗ trợ',
        'investment',
         NULL,
        6,
        1,
        '',
        1,
        1,
        '2022-09-28'
    ),
    (
        8,
        'Menu Category Home',
        'category',
         NULL,
        2,
        1,
        '',
        1,
        1,
        '2022-09-28'
    ),
    (
        9,
        'Menu Header Top',
        'menuTop',
          NULL,
        1,
        1,
        '',
        1,
        1,
        '2022-11-03'
    );