DROP TABLE IF EXISTS public.tb_content;

CREATE TABLE IF NOT EXISTS public.tb_content (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    language_id integer NOT NULL DEFAULT 1,
    page_id integer,
    code character varying(45) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    images character varying(255) COLLATE pg_catalog."default",
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file character varying COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    detail text COLLATE pg_catalog."default",
    author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    views integer DEFAULT 0,
    pin integer NOT NULL DEFAULT 0,
    date timestamp without time zone,
    note text COLLATE pg_catalog."default",
    status smallint DEFAULT 0,
    maker_id integer,
    maker_date timestamp without time zone,
    position integer DEFAULT 0,
    builder text COLLATE pg_catalog."default",
    CONSTRAINT tb_content_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
    IF EXISTS public.tb_content OWNER to postgres;

COMMENT ON TABLE public.tb_content IS 'bảng tin tức';

COMMENT ON COLUMN public.tb_content.id IS 'Số sequence';

COMMENT ON COLUMN public.tb_content.images IS 'Hình ảnh';

COMMENT ON COLUMN public.tb_content.link IS 'Link liên kết';

COMMENT ON COLUMN public.tb_content.detail IS 'Chi tiết';

COMMENT ON COLUMN public.tb_content.description IS 'Mô tả';

COMMENT ON COLUMN public.tb_content.page_id IS 'Nhóm nội dung';

COMMENT ON COLUMN public.tb_content.orders IS 'Thứ tự';

COMMENT ON COLUMN public.tb_content.note IS 'Ghi chú';

COMMENT ON COLUMN public.tb_content.pin IS 'ghim bài viết';

COMMENT ON COLUMN public.tb_content.status IS 'Tình trạng dữ liệu: 1: Active; 0: Inactive';

COMMENT ON COLUMN public.tb_content.maker_id IS 'Người tạo';

COMMENT ON COLUMN public.tb_content.maker_date IS 'Ngày tạo';