-- Table: public.tb_config_address
-- DROP TABLE public.tb_config_address;
CREATE TABLE public.tb_config_address (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    code character varying(45) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    orders integer DEFAULT 0,
    pin integer DEFAULT 0,
    is_delete integer DEFAULT 1,
    note text COLLATE pg_catalog."default",
    status integer DEFAULT 0,
    maker_id bigint NOT NULL,
    maker_date timestamp without time zone,
    language_id bigint DEFAULT 0,
    CONSTRAINT tb_config_address_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
    public.tb_config_address OWNER to postgres;

COMMENT ON TABLE public.tb_config_address IS 'Hệ thống cửa hàng';

COMMENT ON COLUMN public.tb_config_address.id IS 'Số sequence';

COMMENT ON COLUMN public.tb_config_address.phone IS 'Số điện thoại';

COMMENT ON COLUMN public.tb_config_address.email IS 'Email';

COMMENT ON COLUMN public.tb_config_address.address IS 'Địa chỉ liên hệ';

COMMENT ON COLUMN public.tb_config_address.is_delete IS 'Giá trị dữ liệu có được xoá hay không 0: không được xoá 1: được xoá';

COMMENT ON COLUMN public.tb_config_address.status IS 'Tình trạng dữ liệu: 1: Active, 0: Inactive';

COMMENT ON COLUMN public.tb_config_address.maker_id IS 'Người tạo';

COMMENT ON COLUMN public.tb_config_address.maker_date IS 'Ngày tạo';