-- Table: public.tb_product
-- DROP TABLE public.tb_product;
CREATE TABLE public.tb_product (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    language_id integer NOT NULL DEFAULT 1,
    page_id integer,
    code character varying(45) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file character varying COLLATE pg_catalog."default",
    info text COLLATE pg_catalog."default",
    detail text COLLATE pg_catalog."default",
    title character varying(80) COLLATE pg_catalog."default" NULL,
    description character varying(350) COLLATE pg_catalog."default",
    price double precision DEFAULT 0,
    price_sale double precision DEFAULT 0,
    views integer DEFAULT 0,
    pin integer NOT NULL DEFAULT 0,
    date timestamp without time zone,
    note text COLLATE pg_catalog."default",
    status integer DEFAULT 0,
    maker_id integer,
    maker_date timestamp without time zone,
    CONSTRAINT tb_product_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
    public.tb_product OWNER to postgres;

COMMENT ON TABLE public.tb_product IS 'bảng tin tức';

COMMENT ON COLUMN public.tb_product.id IS 'Số sequence';

COMMENT ON COLUMN public.tb_product.page_id IS 'Nhóm nội dung';

COMMENT ON COLUMN public.tb_product.link IS 'Link liên kết';

COMMENT ON COLUMN public.tb_product.info IS 'thông tin chung';

COMMENT ON COLUMN public.tb_product.detail IS 'Chi tiết';

COMMENT ON COLUMN public.tb_product.description IS 'Mô tả';

COMMENT ON COLUMN public.tb_product.pin IS 'ghim bài viết';

COMMENT ON COLUMN public.tb_product.note IS 'Ghi chú';

COMMENT ON COLUMN public.tb_product.status IS 'Tình trạng dữ liệu: 1: Active; 0: Inactive';

COMMENT ON COLUMN public.tb_product.maker_id IS 'Người tạo';

COMMENT ON COLUMN public.tb_product.maker_date IS 'Ngày tạo';