CREATE TABLE public.tb_page (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    parent_id bigint DEFAULT 0,
    code character varying(45) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    images character varying(255) COLLATE pg_catalog."default",
    listimages text COLLATE pg_catalog."default",
    icon character varying(255) COLLATE pg_catalog."default",
    background character varying(255) COLLATE pg_catalog."default",
    link_video character varying(255) COLLATE pg_catalog."default",
    file character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    title_seo character varying(255) COLLATE pg_catalog."default",
    info text COLLATE pg_catalog."default",
    detail text COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    related json,
    list_library json,
    builder text COLLATE pg_catalog."default",
    keywords json,
    type_builder integer DEFAULT 1,
    target_blank integer DEFAULT 0,
    position integer DEFAULT 0,
    type integer DEFAULT 2,
    orders integer DEFAULT 0,
    pin integer DEFAULT 0,
    is_delete integer DEFAULT 1,
    note text COLLATE pg_catalog."default",
    status integer DEFAULT 0,
    maker_id bigint NOT NULL,
    maker_date timestamp without time zone,
    language_id bigint DEFAULT 0,
    CONSTRAINT tb_page_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
    public.tb_page OWNER to postgres;

COMMENT ON COLUMN public.tb_page IS 'Danh sách trang, nhóm/Danh mục';

COMMENT ON COLUMN public.tb_page.id IS 'Số sequence';

COMMENT ON COLUMN public.tb_page.type IS 'Phân loại: 1: Link 2: Page 3: Product 4: Content, 5: Library, 6: Customer';

COMMENT ON COLUMN public.tb_page.parent_id IS 'Id cấp cha của page';

COMMENT ON COLUMN public.tb_page.email IS 'Email';

COMMENT ON COLUMN public.tb_page.is_delete IS 'Giá trị dữ liệu có được xoá hay không 0: không được xoá 1: được xoá';

COMMENT ON COLUMN public.tb_page.status IS 'Tình trạng dữ liệu: 1: Active, 0: Inactive';

COMMENT ON COLUMN public.tb_page.maker_id IS 'Người tạo';

COMMENT ON COLUMN public.tb_page.maker_date IS 'Ngày tạo';