-- DROP TABLE public.tb_redirect;
CREATE TABLE public.tb_redirect (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    status_code integer DEFAULT 200,
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    link_redirect character varying(255) COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default",
    status integer DEFAULT 1,
    maker_id bigint NOT NULL,
    maker_date timestamp without time zone,
    CONSTRAINT tb_redirect_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
    public.tb_redirect OWNER to postgres;

COMMENT ON COLUMN public.tb_redirect.id IS 'Số sequence';

COMMENT ON COLUMN public.tb_redirect.status_code IS 'trạng thái đường dẫn';

COMMENT ON COLUMN public.tb_redirect.link IS 'link cần chuyển tiếp';

COMMENT ON COLUMN public.tb_redirect.link_redirect IS 'Link chuyển tiếp';

COMMENT ON COLUMN public.tb_redirect.status IS 'Tình trạng dữ liệu: 1: Active, 0: Inactive';

COMMENT ON COLUMN public.tb_redirect.maker_id IS 'Người tạo';

COMMENT ON COLUMN public.tb_redirect.maker_date IS 'Ngày tạo';