DROP TABLE public.tb_slide;

CREATE TABLE public.tb_slide (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    type integer DEFAULT 0,
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title_seo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description character varying(350) COLLATE pg_catalog."default" NOT NULL,
    images character varying(255) COLLATE pg_catalog."default" NOT NULL,
    images_mobile character varying(255) COLLATE pg_catalog."default" NOT NULL,
    position integer DEFAULT 0,
    orders integer DEFAULT 0,
    is_delete integer DEFAULT 1,
    note text COLLATE pg_catalog."default",
    status integer DEFAULT 0,
    maker_id bigint NOT NULL,
    maker_date timestamp without time zone,
    language_id bigint DEFAULT 0,
    CONSTRAINT tb_slide_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE
    public.tb_slide OWNER to postgres;

COMMENT ON COLUMN public.tb_slide.id IS 'Số sequence';

COMMENT ON COLUMN public.tb_slide.type IS  'Phân loại 1: slide, 2: banner';

COMMENT ON COLUMN public.tb_slide.images IS  'Hình ảnh desktop';

COMMENT ON COLUMN public.tb_slide.images_mobile IS  'Hình ảnh mobile';

COMMENT ON COLUMN public.tb_slide.is_delete IS 'Giá trị dữ liệu có được xoá hay không 0: không được xoá 1: được xoá';

COMMENT ON COLUMN public.tb_slide.status IS 'Tình trạng dữ liệu: 1: Active, 0: Inactive';

COMMENT ON COLUMN public.tb_slide.maker_id IS 'Người tạo';

COMMENT ON COLUMN public.tb_slide.maker_date IS 'Ngày tạo';